In [ ]:
import pandas as pd
import numpy as np
import plotly.express as px #Criação de gráficos dinamicos
import plotly.graph_objects as go #Concatenização de Dados
from sklearn.preprocessing import StandardScaler # Padronização de Dados
from sklearn.cluster  import KMeans 

In [ ]:
#Abrindo  o Arquivo de Dados
base_iris = pd.read_csv('base_iris.csv', sep = ";")

In [ ]:
base_iris.head()

sepal length  sepal width  petal length  petal width        Class
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [ ]:
base_iris.shape

(150, 5)

In [ ]:
 #Verificando a Base das flores
 base_iris['Class'].unique()

array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype=object)

# Realizando um agrupamento de pétalas

In [ ]:
# criando Variável X com as colunas petal lenght e petal width 
X_petala = base_iris.iloc[:,[2,3]].values
X_petala[:10]

array([[1.4, 0.2],
       [1.4, 0.2],
       [1.3, 0.2],
       [1.5, 0.2],
       [1.4, 0.2],
       [1.7, 0.4],
       [1.4, 0.3],
       [1.5, 0.2],
       [1.4, 0.2],
       [1.5, 0.1]])

# Normalização dos dados

In [ ]:
normalizar_dados = StandardScaler()
X_petala = normalizar_dados.fit_transform(X_petala)
X_petala[:10]

array([[-1.3412724 , -1.31297673],
       [-1.3412724 , -1.31297673],
       [-1.39813811, -1.31297673],
       [-1.2844067 , -1.31297673],
       [-1.3412724 , -1.31297673],
       [-1.17067529, -1.05003079],
       [-1.3412724 , -1.18150376],
       [-1.2844067 , -1.31297673],
       [-1.3412724 , -1.31297673],
       [-1.2844067 , -1.4444497 ]])

# Calculando o numero de Clusters

In [ ]:
wcss_petala = []#criando uma Lista Vazia
for i in range(1,11):
  kmeans_petala = KMeans(n_clusters=i, random_state=0) #executa o kmeans para todos os clusters e random_state = 0 para fixar e obter os mesmos resultados
  kmeans_petala.fit(X_petala) #Realizando o Treinamento
  wcss_petala.append(kmeans_petala.inertia_) #Adiciona na lista os valores do WCSS  

In [ ]:
#vizualizando os valores de WCSS
for i in range(len(wcss_petala)):
  print('Cluster:',i, ' - valor do wcss:', wcss_petala[i])

Cluster: 0  - valor do wcss: 300.0
Cluster: 1  - valor do wcss: 54.145847013449895
Cluster: 2  - valor do wcss: 18.046983891906272
Cluster: 3  - valor do wcss: 12.307440251261845
Cluster: 4  - valor do wcss: 9.181131495513899
Cluster: 5  - valor do wcss: 7.215096212730807
Cluster: 6  - valor do wcss: 6.03938449718369
Cluster: 7  - valor do wcss: 5.170633181510533
Cluster: 8  - valor do wcss: 4.433073835157262
Cluster: 9  - valor do wcss: 3.914827472555978


# Criando Gráficos Para Vizualizar Melhor

In [ ]:
grafico_cotovelo_petala = px.line(x= range(1,11), y= wcss_petala)
grafico_cotovelo_petala.show()

In [ ]:
kmeans_petala = KMeans(n_clusters=3, random_state=0)
label_cluster_petala = kmeans_petala.fit_predict(X_petala)

In [ ]:
#verificando a classificação dos Clusters
label_cluster_petala

In [ ]:
centroides_petala = kmeans_petala.cluster_centers_
centroides_petala

array([[-1.30487835, -1.25512862],
       [ 1.02813193,  1.12749028],
       [ 0.30564587,  0.16609419]])

# Gráfico de Agrupamento  Das Caracteristicas  do tamanho e comprimento das Pétalas

In [ ]:
grafico_petala = px.scatter(x = X_petala[:,0], y = X_petala[:,1], color= label_cluster_petala)
grafico_centroide_petala = px.scatter(x = centroides_petala[:,0], y = centroides_petala[:,1], size=[7,7,7])
grafico_final_petala = go.Figure(data = grafico_petala.data + grafico_centroide_petala.data)
grafico_final_petala.show()

# Realizando o Agrupamento com dados da Sépala 

In [ ]:
# realizando o agrupamento da  sepala
X_sepala = base_iris.iloc[:,[0,1]].values
X_sepala[:10]

array([[5.1, 3.5],
       [4.9, 3. ],
       [4.7, 3.2],
       [4.6, 3.1],
       [5. , 3.6],
       [5.4, 3.9],
       [4.6, 3.4],
       [5. , 3.4],
       [4.4, 2.9],
       [4.9, 3.1]])

In [ ]:
#calcular o WCSS
wcss_sepala = []
for i in range(1,11):
  kmeans_sepala = KMeans(n_clusters=i,random_state= 0 )# executar o kmeans em 10 clusters e fixar os resultados
  kmeans_sepala.fit(X_sepala) #treinamento
  wcss_sepala.append(kmeans_sepala.inertia_)


In [ ]:
for i in range(len(wcss_sepala)):
  print('Cluster: ', i, 'valor do wcss: ', wcss_sepala[i])

Cluster:  0 valor do wcss:  130.18093333333334
Cluster:  1 valor do wcss:  57.982406042078765
Cluster:  2 valor do wcss:  37.12370212765957
Cluster:  3 valor do wcss:  27.948333333333338
Cluster:  4 valor do wcss:  20.94968664636183
Cluster:  5 valor do wcss:  17.23869523809524
Cluster:  6 valor do wcss:  14.631909607059608
Cluster:  7 valor do wcss:  12.764068676332741
Cluster:  8 valor do wcss:  11.161008019758023
Cluster:  9 valor do wcss:  9.65434920634921


In [ ]:
# grafico cotovelo
grafico_cotovelo_sepala = px.line(x= range(1,11), y = wcss_sepala)
grafico_cotovelo_sepala.show()

#Executando o K-means 

In [ ]:
kmeans_sepala = KMeans(n_clusters=3, random_state=0)
label_cluster_sepala = kmeans_sepala.fit_predict(X_sepala)

In [ ]:
label_cluster_sepala

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 2, 1, 2, 1, 2, 1, 2, 2, 2, 2, 2, 2, 1,
       2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 1, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 2, 1, 1, 1, 1, 2, 1, 1, 1,
       1, 1, 1, 2, 2, 1, 1, 1, 1, 2, 1, 2, 1, 2, 1, 1, 2, 2, 1, 1, 1, 1,
       1, 2, 2, 1, 1, 1, 2, 1, 1, 1, 2, 1, 1, 1, 2, 1, 1, 2], dtype=int32)

In [ ]:
centroides_sepala = kmeans_sepala.cluster_centers_
centroides_sepala

array([[5.006     , 3.418     ],
       [6.81276596, 3.07446809],
       [5.77358491, 2.69245283]])

#Grafico de agrupamento e caracteristica do tamanho das sepalas 

In [ ]:
grafico_sepala = px.scatter(x = X_sepala[:,0], y = X_sepala[:,1], color= label_cluster_sepala)
grafico_centroide_sepala = px.scatter(x = centroides_sepala[:,0], y = centroides_sepala[:,1], size=[7,7,7])
grafico_final_sepala = go.Figure(data= grafico_sepala.data + grafico_centroide_sepala.data)
grafico_final_sepala.show()